version: 1
release:
  # Branch configuration
  branch: main

  # Version bump type
  defaultBump: patch

  # Version file updates
  version:
    files:
      - path: 'package.json'
        pattern: "\"version\":\\s*\"(?<version>[^\"]+)\""
        template: '"version": "${version}"'

  # Changelog configuration
  changelog:
    enabled: true
    template: conventional

  # # Pre-release checks
  # checks:
  #   - type: lint
  #     command: 'npm run lint'
  #   - type: test
  #     command: 'npm test'
  #   - type: build
  #     command: 'npm run build'

  # Release actions actions
  actions:
    - type: git-tag
    - type: commit-push
    - type: github-release
