# This file is generated by Nx.
#
# Build the docker image with `npx nx docker-build godeploy-api`.
# Tip: Modify "docker-build" options in project.json to change docker build args.
#
# Run the container with `docker run -p 3000:3000 -t godeploy-api`.
FROM docker.io/node:lts-alpine

ENV HOST=0.0.0.0
ENV PORT=3000

WORKDIR /app

RUN addgroup --system godeploy-api && \
          adduser --system -G godeploy-api godeploy-api

COPY apps/godeploy-api/dist godeploy-api/
RUN chown -R godeploy-api:godeploy-api .

# You can remove this install step if you build with `--bundle` option.
# The bundled output will include external dependencies.
RUN npm --prefix godeploy-api --omit=dev -f install

CMD [ "node", "godeploy-api" ]
